USE TN_CSDLPT﻿
GO

SELECT MAGV FROM CAUHOI
SELECT MAGV FROM GIAOVIEN

SELECT MAGV FROM CAUHOI
EXCEPT
SELECT MAGV FROM GIAOVIEN

SELECT MAGV FROM CAUHOI WHERE MAGV NOT IN (SELECT MAGV FROM GIAOVIEN)

--SELECT * FROM GIAOVIEN
--	WHERE MAGV = 'TH122' OR MAGV = 'TH124'

SELECT * FROM GIAOVIEN
SELECT * FROM CAUHOI
	WHERE MAGV = 'TH122' OR MAGV = 'TH124'

UPDATE CAUHOI
	SET MAGV = 'TH123'
	WHERE MAGV = 'TH122' OR MAGV = 'TH124';

-- Tạo kết nối giữa CAUHOI và GIAOVIEN

SELECT MALOP FROM LOP

SELECT MALOP FROM SINHVIEN WHERE MALOP NOT IN (SELECT MALOP FROM LOP)

UPDATE SINHVIEN
	SET MALOP = 'TH14'
	WHERE MALOP = 'TH04'

UPDATE SINHVIEN
	SET MALOP = 'TH15'
	WHERE MALOP = 'TH05'

UPDATE SINHVIEN
	SET MALOP = 'TH16'
	WHERE MALOP = 'TH06'

-- Tạo kết nối giữa SINHVIEN và LOP

CREATE PROC ThemMH
	@MASV nvarchar(8)
AS
BEGIN 
	DECLARE @NgayThi DATETIME = GETDATE();
	DECLARE @LanThi INT = 1;

	-- Chèn các môn học hiện có cho sinh vien bản điểm
	INSERT INTO BANGDIEM (MASV, MAMH, LAN, NGAYTHI, DIEM, BAITHI)
	SELECT @MASV, MAMH, @LanThi, @NgayThi, NULL, NULL
	FROM MONHOC

END;

EXEC ThemMH '002'

-- Tạo trigger: Nếu người dùng cung cấp diểm bị sai thì để điểm mặc định hoặc 0 hoặc 10
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER CheckWrong
   ON BANGDIEM
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	UPDATE BANGDIEM
	SET DIEM = CASE
			WHEN inserted.DIEM < 0 THEN 0
			WHEN inserted.DIEM > 10 THEN 10
			ELSE inserted.DIEM
		END,
		LAN = CASE
			WHEN inserted.LAN > 2 THEN 2
			ELSE inserted.LAN
		END
	FROM inserted
	WHERE BANGDIEM.MASV = inserted.MASV AND
			BANGDIEM.MAMH = inserted.MAMH AND
			BANGDIEM.NGAYTHI = inserted.NGAYTHI
END
GO

/*
CREATE TRIGGER CheckWrongPoint
	ON BANGDIEM
	INSTEAD OF INSERT, UPDATE
AS
BEGIN
	SET NOCOUNT ON;

	INSERT BANGDIEM(MASV, MAMH, LAN, NGAYTHI, BAITHI, DIEM)
	SELECT i.MASV, i.MAMH, i.LAN, i.NGAYTHI, i.BAITHI,
		CASE
			WHEN i.DIEM < 0 THEN 0
			WHEN i.DIEM > 10 THEN 10
			ELSE i.DIEM
		END

	FROM inserted i
END

-- Bạn nhận được lỗi này vì bảng `BANGDIEM` có khóa ngoại (FOREIGN KEY) với tùy chọn xóa hoặc cập nhật liên tiếp (cascading DELETE or UPDATE).

*/

UPDATE BANGDIEM
	SET DIEM = -1
	WHERE MASV = '002' AND MAMH = 'AVCB' AND LAN = 1

-- Tạo trigger:  Nếu người dùng nhập lần thi trên 2 thì sửa lần thi lại là 2

/*
ALTER TRIGGER CheckWrongLanThi
   ON BANGDIEM
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;

	UPDATE BANGDIEM
	SET LAN = 2
	FROM inserted
	WHERE BANGDIEM.MASV = inserted.MASV AND
			BANGDIEM.MAMH = inserted.MAMH AND
			BANGDIEM.NGAYTHI = inserted.NGAYTHI AND
			inserted.LAN > 2;
END
GO
*/

UPDATE BANGDIEM
	SET LAN = 3
	WHERE MASV = '002' AND MAMH = 'AVCB' AND NGAYTHI = '2024-07-16'