USE TN_CSDLPT﻿
GO

SELECT MAMH FROM MONHOC

SELECT * FROM CAUHOI WHERE MAMH NOT IN (SELECT MAMH FROM MONHOC)

UPDATE CAUHOI
	SET MAMH = 'DLPT'
	WHERE MAMH = 'CDLPT'

UPDATE CAUHOI
	SET MAMH = 'CSDL'
	WHERE MAMH = 'CSD'

ALTER TABLE CAUHOI
	ADD CONSTRAINT FK_CAUHOI_MONHOC FOREIGN KEY (MAMH)
		REFERENCES MONHOC(MAMH)

SELECT * FROM GIAOVIEN_DANGKY WHERE MAGV NOT IN (SELECT MAGV FROM GIAOVIEN)

