CREATE DATABASE QLThiTNCoso1
GO

USE QLThiTNCoso1
GO

SELECT DISTINCT * INTO COSO
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[COSO]
		WHERE TENCS = 'CO SO 1'

ALTER TABLE COSO
	ADD CONSTRAINT PK_COSO PRIMARY KEY (MACS)

SELECT DISTINCT KHOA.* INTO KHOA
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[KHOA]
		INNER JOIN COSO ON COSO.MACS = KHOA.MACS

ALTER TABLE KHOA
	ADD CONSTRAINT PK_KHOA PRIMARY KEY (MAKH),
		CONSTRAINT FK_KHOA_COSO FOREIGN KEY (MACS)
			REFERENCES COSO(MACS)

--DROP TABLE GIAOVIEN

SELECT DISTINCT GIAOVIEN.* INTO GIAOVIEN
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[GIAOVIEN]
		INNER JOIN KHOA ON KHOA.MAKH = GIAOVIEN.MAKH

ALTER TABLE GIAOVIEN
	ADD CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV),
		CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY (MAKH)
			REFERENCES KHOA(MAKH)

SELECT * INTO MONHOC
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[MONHOC]

ALTER TABLE MONHOC
	ADD CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH)

SELECT DISTINCT LOP.* INTO LOP
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[LOP]
	INNER JOIN KHOA ON KHOA.MAKH = LOP.MAKH

ALTER TABLE LOP
	ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP),
		CONSTRAINT FK_LOP_KHOA FOREIGN KEY (MAKH)
			REFERENCES KHOA(MAKH)

SELECT DISTINCT SINHVIEN.* INTO SINHVIEN
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[SINHVIEN]
	INNER JOIN LOP ON LOP.MALOP = SINHVIEN.MALOP

ALTER TABLE SINHVIEN
	ADD CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV),
		CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP)
			REFERENCES LOP(MALOP)

SELECT BANGDIEM.* INTO BANGDIEM
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[BANGDIEM]
	INNER JOIN SINHVIEN ON SINHVIEN.MASV = BANGDIEM.MASV

ALTER TABLE BANGDIEM
	ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MASV)
			REFERENCES SINHVIEN(MASV),
		CONSTRAINT FK_BANGDIEM_MONHOC FOREIGN KEY (MAMH)
			REFERENCES MONHOC(MAMH)

DROP TABLE CAUHOI

SELECT CAUHOI.* INTO CAUHOI
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[CAUHOI]
	INNER JOIN GIAOVIEN ON GIAOVIEN.MAGV = CAUHOI.MAGV

ALTER TABLE CAUHOI
	ADD CONSTRAINT PK_CAUHOI PRIMARY KEY (MACH)

ALTER TABLE CAUHOI
	ADD CONSTRAINT FK_CAUHOI_MONHOC FOREIGN KEY (MAMH)
			REFERENCES MONHOC(MAMH)

ALTER TABLE CAUHOI
		ADD CONSTRAINT FK_CAUHOI_GIAOVIEN FOREIGN KEY (MAGV)
			REFERENCES GIAOVIEN(MAGV)

SELECT DISTINCT GIAOVIEN_DANGKY.* INTO GIAOVIEN_DANGKY
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[GIAOVIEN_DANGKY]

/*
SELECT *
	FROM [LINK2008].[TN_CSDLPT﻿].[dbo].[GIAOVIEN_DANGKY]

*/

ALTER TABLE GIAOVIEN_DANGKY
	ADD CONSTRAITN FK_GV_DK_GIAOVIEN FOREIGN KEY (MAGV)
		REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIAOVIEN_DANGKY
	ADD CONSTRAINT FK_GV_DK_LOP FOREIGN KEY (MALOP)
			REFERENCES LOP(MALOP)
		
ALTER TABLE GIAOVIEN_DANGKY
	ADD CONSTRAINT FK_GV_DK_MONHOC FOREIGN KEY (MAMH)
			REFERENCES MONHOC(MAMH)