CREATE DATABASE QLVT2_2008
GO

USE QLVT2_2008
GO

SELECT * INTO [CHINHANH]
	FROM [LINK_2008].[QLVT_2008].[dbo].[CHINHANH]
	WHERE DIACHI LIKE N'%tp. Cần Thơ%'


ALTER TABLE CHINHANH
	ADD CONSTRAINT PK_CHINHANH PRIMARY KEY (MACN)

SELECT DISTINCT [KHO].* INTO KHO
	FROM [LINK_2008].[QLVT_2008].[dbo].[KHO]
	INNER JOIN CHINHANH ON KHO.MACN = CHINHANH.MACN

ALTER TABLE KHO
	ADD CONSTRAINT PK_KHO PRIMARY KEY (MAKHO)

ALTER TABLE KHO
	ADD CONSTRAINT FK_KHO_CHINHANH FOREIGN KEY (MACN)
		REFERENCES CHINHANH(MACN)


SELECT DISTINCT [NHANVIEN].* INTO [NHANVIEN]
	FROM [LINK_2008].[QLVT_2008].[dbo].[NHANVIEN]
	INNER JOIN CHINHANH ON [NHANVIEN].MACN = CHINHANH.MACN

SELECT * FROM NHANVIEN

ALTER TABLE NHANVIEN
	ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
	CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY (MACN)
		REFERENCES CHINHANH(MACN)


SELECT * FROM [LINK_2008].[QLVT_2008].[dbo].PhieuNhap

SELECT DISTINCT PhieuNhap.* INTO PhieuNhap
	FROM [LINK_2008].[QLVT_2008].[dbo].PhieuNhap
	INNER JOIN NHANVIEN ON NHANVIEN.MANV = PhieuNhap.MANV

SELECT * FROM [dbo].PhieuNhap

ALTER TABLE PhieuNhap
	ADD CONSTRAINT PK_PhieuNhap PRIMARY KEY (MAPN),
	CONSTRAINT FK_PhieuNhap_NHANVIEN FOREIGN KEY (MANV)
		REFERENCES NHANVIEN(MANV)

SELECT DISTINCT CTPN.* INTO CTPN
	FROM [LINK_2008].[QLVT_2008].[dbo].CTPN
	INNER JOIN PhieuNhap ON PhieuNhap.MAPN = CTPN.MAPN

SELECT DISTINCT VATTU.* INTO VATTU
	FROM [LINK_2008].[QLVT_2008].[dbo].VATTU
	INNER JOIN CTPN ON CTPN.MAVT = VATTU.MAVT

ALTER TABLE VATTU
	ADD CONSTRAINT PK_VATTU PRIMARY KEY (MAVT)

ALTER TABLE CTPN
	ADD CONSTRAINT FK_CTPN_PhieuNhap FOREIGN KEY (MAPN)
		REFERENCES PhieuNhap(MAPN),
		CONSTRAINT FK_CTPN_VATTU FOREIGN KEY (MAVT)
		REFERENCES VATTU(MAVT)

SELECT DISTINCT CTDDH.* INTO CTDDH
	FROM [LINK_2008].[QLVT_2008].[dbo].CTDDH
	INNER JOIN VATTU ON VATTU.MAVT = CTDDH.MAVT

SELECT DISTINCT DatHang.* INTO DatHang
	FROM [LINK_2008].[QLVT_2008].[dbo].DatHang
	INNER JOIN NHANVIEN ON NHANVIEN.MANV = DatHang.MANV

ALTER TABLE DatHang
	ADD CONSTRAINT PK_DatHang PRIMARY KEY (MasoDDH)

DROP TABLE CTDDH

SELECT DISTINCT CTDDH.* INTO CTDDH
	FROM [LINK_2008].[QLVT_2008].[dbo].CTDDH
	INNER JOIN DatHang ON DatHang.MasoDDH = CTDDH.MasoDDH

--ALTER TABLE CTPN
--	DROP CONSTRAINT FK_CTPN_VATTU

DROP TABLE VATTU

SELECT DISTINCT VATTU.* INTO VATTU
	FROM [LINK_2008].[QLVT_2008].[dbo].VATTU
	INNER JOIN CTDDH ON CTDDH.MAVT = VATTU.MAVT

ALTER TABLE VATTU
	ADD CONSTRAINT PK_VATTU PRIMARY KEY (MAVT)

DROP TABLE CTPN

DROP TABLE PhieuNhap

SELECT DISTINCT CTPN.* INTO CTPN
	FROM [LINK_2008].[QLVT_2008].[dbo].CTPN
	INNER JOIN VATTU ON VATTU.MAVT = CTPN.MAVT

SELECT DISTINCT PhieuNhap.* INTO PhieuNhap
	FROM [LINK_2008].[QLVT_2008].[dbo].PhieuNhap
	INNER JOIN CTPN ON CTPN.MAPN = CTPN.MAPN

ALTER TABLE PhieuNhap
	ADD CONSTRAINT PK_PhieuNhap PRIMARY KEY (MAPN),
	CONSTRAINT FK_PhieuNhap_NHANVIEN FOREIGN KEY (MANV)
		REFERENCES NHANVIEN(MANV)
-- The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_PhieuNhap_NHANVIEN". The conflict occurred in database "QLVT2_2008", table "dbo.NHANVIEN", column 'MANV'.

ALTER TABLE PhieuNhap
	ADD CONSTRAINT PK_PhieuNhap PRIMARY KEY (MAPN)

ALTER TABLE CTPN
	ADD CONSTRAINT FK_CTPN_PhieuNhap FOREIGN KEY (MAPN)
		REFERENCES PhieuNhap(MAPN),
		CONSTRAINT FK_CTPN_VATTU FOREIGN KEY (MAVT)
		REFERENCES VATTU(MAVT)

ALTER TABLE CTDDH
	ADD CONSTRAINT FK_CTDDH_DatHang FOREIGN KEY (MasoDDH)
		REFERENCES DatHang(MasoDDH),
		CONSTRAINT FK_CTDDH_VATTU FOREIGN KEY(MAVT)
		REFERENCES VATTU(MAVT)

ALTER TABLE DatHang
	ADD CONSTRAINT FK_DatHang_NHANVIEN FOREIGN KEY (MANV)
		REFERENCES NHANVIEN(MANV)


SELECT DISTINCT PhieuXuat.* INTO PhieuXuat
	FROM [LINK_2008].[QLVT_2008].[dbo].PhieuXuat
	INNER JOIN NHANVIEN ON NHANVIEN.MANV = PhieuXuat.MANV

ALTER TABLE PhieuXuat
	ADD CONSTRAINT PK_PhieuXuat PRIMARY KEY (MAPX),
		CONSTRAINT FK_PhieuXuat FOREIGN KEY (MANV)
			REFERENCES NHANVIEN(MANV)

SELECT DISTINCT CTPX.* INTO CTPX
	FROM [LINK_2008].[QLVT_2008].[dbo].CTPX
	INNER JOIN PhieuXuat ON PhieuXuat.MAPX = CTPX.MAPX

ALTER TABLE CTPX
	ADD CONSTRAINT FK_CTPX_PhieuXuat FOREIGN KEY (MAPX)
			REFERENCES PhieuXuat(MAPX),
		CONSTRAINT FK_CTPX_VATTU FOREIGN KEY (MAVT)
			REFERENCES VATTU(MAVT)

ALTER TABLE PhieuNhap
	ADD CONSTRAINT FK_PhieuNhap_DatHang FOREIGN KEY (MasoDDH)
		REFERENCES DatHang(MasoDDH)