use QLDA
GO

alter table NHANVIEN
ADD FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
ON DELETE CASCADE
ON UPDATE CASCADE

alter table NHANVIEN
ADD FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE DUAN
ALTER COLUMN MAPB VARCHAR(5) NOT NULL

SELECT * FROM DUAN
SELECT * FROM PHONGBAN

UPDATE DUAN
SET MAPB = 'NS'
WHERE MAPB NOT IN (SELECT MAPB FROM PHONGBAN)

ALTER TABLE DUAN 
ADD FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
ON DELETE CASCADE
ON UPDATE CASCADE

ALTER TABLE PHANCONG
ALTER COLUMN MADA VARCHAR(25) NOT NULL

ALTER TABLE PHANCONG
ALTER COLUMN MANV VARCHAR(5) NOT NULL

ALTER TABLE PHANCONG 
ADD FOREIGN KEY (MADA) REFERENCES DUAN(MADA)
ON DELETE CASCADE 
ON UPDATE CASCADE

ALTER TABLE PHANCONG 
ADD FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ON DELETE NO ACTION
ON UPDATE NO ACTION

SELECT * FROM CHUCVU
SELECT * FROM PHONGBAN

CREATE TRIGGER PHANTAN
ON [QLDA].[dbo].[DUAN]
AFTER INSERT 
AS
BEGIN
	SELECT * FROM INSERTED 
	BEGIN
		INSERT INTO [LAPTOP-Q2014BBC\SITE].[QLDuAn].[dbo].[DUAN]
		SELECT * FROM INSERTED 
	END
END

CREATE TRIGGER PHANTAN2
ON [QLDA].[dbo].[DUAN]
AFTER DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	IF EXISTS (SELECT * FROM DELETED)
	BEGIN 
		DELETE FROM [LAPTOP-Q2014BBC\SITE].[QLDuAn].[dbo].[DUAN]
		WHERE MADA IN (SELECT MADA FROM DELETED)
	END
	END

SELECT * FROM DUAN
INSERT INTO DUAN VALUES
('SHINGU',N'123',N'AMPHU',10000,'2003-01-01','2004-01-01','KH')

DELETE FROM DUAN WHERE MADA = 'SHINGU'

CREATE TRIGGER PHANTAN3
ON [QLDA].[dbo].[DUAN]
AFTER UPDATE
AS 
BEGIN
	SET NOCOUNT ON;
	UPDATE A
	SET A.MADA = B.MADA,
		A.TENDA = B.TENDA,
		A.DIADIEM = B.DIADIEM,
		A.KINHPHI = B.KINHPHI,
		A.TGBATDAU = B.TGBATDAU,
		A.TGKETTHUC = B.TGKETTHUC,
		A.MAPB = B.MAPB
	FROM
		[LAPTOP-Q2014BBC\SITE].[QLDuAn].[dbo].[DUAN] A
		INNER JOIN INSERTED B ON A.MADA = (SELECT MADA FROM DELETED)
	END

	SELECT * FROM DUAN

	SELECT @@servername
