CREATE DATABASE QLDuAn
USE QLDuAn

SELECT A.* INTO DUAN FROM [LAPTOP-Q2014BBC\SERVER].[QLDA].[dbo].[DUAN] A 
INNER JOIN [LAPTOP-Q2014BBC\SERVER].[QLDA].[dbo].[PHONGBAN] B
ON A.MAPB = B.MAPB
WHERE A.KINHPHI <= 200000 AND B.TENPB <> N'Nhân sự' AND YEAR(A.TGBATDAU) >= 2000

USE QLDUAN
SELECT * FROM DUAN

CREATE TRIGGER PHANTAN4
ON [QLDuAn].[dbo].[DUAN]
AFTER INSERT 
AS
BEGIN
	SELECT * FROM INSERTED 
	BEGIN
		INSERT INTO [LAPTOP-Q2014BBC\SERVER].[QLDA].[dbo].[DUAN]
		SELECT * FROM INSERTED 
	END
END

INSERT INTO DUAN VALUES
('SHINGU',N'123',N'AMPHU',10000,'2003-01-01','2004-01-01','KH')

SELECT @@servername
SP_DROPSERVER 'LAPTOP-Q2014BBC\SITE'

SP_ADDSERVER 'LAPTOP-Q2014BBC\SITE', local