CREATE DATABASE QLHS2022
GO

USE QLHS2022
GO

SELECT DISTINCT * INTO HK_NH
	FROM [SERVER21022008].[QLHS].[dbo].[HK_NH]
	WHERE '2021' < NAMHOC AND NAMHOC < '2022'
GO

ALTER TABLE HK_NH
	ADD CONSTRAINT PK_HK_NH PRIMARY KEY (MAHK_NH)
GO

SELECT DISTINCT HOCSINH_LOP.* INTO HOCSINH_LOP
		FROM [SERVER21022008].[QLHS].[dbo].[HOCSINH_LOP], HK_NH 
		WHERE HOCSINH_LOP.MAHK_NH = HK_NH.MAHK_NH
GO

ALTER TABLE HOCSINH_LOP ADD 
	CONSTRAINT PK_HOCSINH_LOP PRIMARY KEY (MAHS, MAHK_NH),
	CONSTRAINT FK_HOCSINH_LOP_HK_NH FOREIGN KEY (MAHK_NH)
		REFERENCES HK_NH(MAHK_NH)
GO



SELECT DISTINCT HOCBA.* INTO HOCBA
	FROM [SERVER21022008].[QLHS].[dbo].[HOCBA], HK_NH
	WHERE HOCBA.MAHK_NH = HK_NH.MAHK_NH
GO

ALTER TABLE HOCBA ADD
	CONSTRAINT PK_HOCBA PRIMARY KEY (MAHS, MAHK_NH),
	CONSTRAINT FK_HOCBA 
GO


