create database site1
go
use site1
go
select * into MONHOC from [LINK_SV2_S1].QLThiTN.dbo.MONHOC 
select * into COSO from [LINK_SV2_S1].QLThiTN.dbo.COSO where TENCS='CO SO 1'
select KHOA.* into KHOA from [LINK_SV2_S1].QLThiTN.dbo.KHOA,COSO where COSO.MACS=KHOA.MACS
select GIAOVIEN.* into GIAOVIEN from [LINK_SV2_S1].QLThiTN.dbo.GIAOVIEN,KHOA where KHOA.MAKH=GIAOVIEN.MAKH
select LOP.* into LOP from [LINK_SV2_S1].QLThiTN.dbo.LOP,KHOA where LOP.MAKH=KHOA.MAKH
select GIAOVIEN_DANGKY.* into GIAOVIEN_DANGKY from [LINK_SV2_S1].QLThiTN.dbo.GIAOVIEN_DANGKY,LOP,GIAOVIEN where GIAOVIEN_DANGKY.MALOP=LOP.MALOP and GIAOVIEN_DANGKY.MAGV=GIAOVIEN.MAGV
select SINHVIEN.* into SINHVIEN from [LINK_SV2_S1].QLThiTN.dbo.SINHVIEN,LOP where SINHVIEN.MALOP=LOP.MALOP
select BANGDIEM.* into BANGDIEM from [LINK_SV2_S1].QLThiTN.dbo.BANGDIEM,SINHVIEN where BANGDIEM.MASV=SINHVIEN.MASV
select CAUHOI.* into CAUHOI from [LINK_SV2_S1].QLThiTN.dbo.CAUHOI,GIAOVIEN where CAUHOI.MAGV=GIAOVIEN.MAGV